\documentclass{article}

\begin{document}
\usepackage{natbib}
\bibliographystyle{apa}

<<title, child='_title.Rnw'>>=
@

\section{Abstract}
<<abstract,child='_abstract.Rnw'>>=
@

\section{Introduction}
<<introduction,child='_introduction.Rnw'>>=
@

\section{Methods}
<<methods,child='_methods.Rnw'>>=
@

\section{Results}
<<results,child='_results.Rnw'>>=
@

\section{Discussion}
<<discussion,child='_discussion.Rnw'>>=
@

\section{Funding}
<<funding,child='_funding.Rnw'>>=
@

}

\end{document}
